[env]
_.python.venv = { path = ".venv", create = true }

[tools]
python = "3.14.2"
uv = "latest"
node = "24"
terraform = "1.14.3"
[tasks]
install_deps = "uv pip install pre-commit ansible-core detect-secrets"
